version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    reviewers:
      - "ojaha065"
    ignore:
      - dependency-name: "telegraf"
        versions: ["4.x"]